// src/app/components/work/work/work.component.ts
import { Component, OnInit } from '@angular/core';
import {AngularFirestore} from '@angular/fire/compat/firestore';
import {combineLatest, map, mergeMap, of, switchMap} from 'rxjs';
import {DatePipe} from '@angular/common';

@Component({
  selector: 'app-work',
  templateUrl: './work.component.html',
  styleUrls: ['./work.component.sass'],
  providers: [DatePipe]
})
export class WorkComponent implements OnInit {
  loaded  = false
  work = null
  constructor(private afs: AngularFirestore,
              private datePipe: DatePipe) { }

  ngOnInit() {
    this.afs.collection('work').valueChanges({ idField: 'id' }).subscribe((items: any[]) => {
      this.loaded = false
      if(items) {
        this.work = items.sort((a, b) => {
          return new Date(a.from) > new Date(b.from) ? -1 : 1
        })
        this.loaded = true
      }
    })
  }
  determineTo(date) {
    if(date) {
      return date === 'present' ? 'present' : this.datePipe.transform(date, 'MMMM y')
    } else {
      return ''
    }
  }
}

<div *ngIf="work; else loadingSpinner">
  <mat-card>
    <mat-card-title>Keywords:</mat-card-title>
    <mat-chip-list aria-label="keywords">
      <mat-chip>Java</mat-chip><mat-chip>Angular</mat-chip><mat-chip>Javascript</mat-chip><mat-chip>PCF</mat-chip>
      <mat-chip>Firebase</mat-chip><mat-chip>Typescript</mat-chip><mat-chip>CI/CD</mat-chip><mat-chip>Kotlin</mat-chip>
      <mat-chip>Firestore</mat-chip><mat-chip>AWS</mat-chip><mat-chip>PWA</mat-chip><mat-chip>Spring Boot</mat-chip>
      <mat-chip>Rest API</mat-chip><mat-chip>DB2</mat-chip><mat-chip>SQL</mat-chip><mat-chip>NoSQL</mat-chip>
      <mat-chip>Git</mat-chip>
    </mat-chip-list>
  </mat-card>
  <div *ngIf="loaded">
    <div *ngFor="let workItem of work; index as i;">
      <mat-card>
        <mat-card-title>
          <div>{{workItem.workplace}}</div>
          <div style="font-size: medium">
            {{workItem.from | date:'MMMM y' }} to {{determineTo(workItem.to)}}
          </div>
        </mat-card-title>
        <mat-card-subtitle>{{workItem.position}}</mat-card-subtitle>
        <mat-card-content>
          <app-work-description [id]="workItem.id"></app-work-description>
        </mat-card-content>
      </mat-card>
    </div>
  </div>

</div>
<ng-template #loadingSpinner>
  <div class="spinner">
    <mat-spinner></mat-spinner>
  </div>
</ng-template>

// src/app/work/page.tsx
import Card from '@/components/Card'
import WorkList from '@/components/WorkList'
import styles from './page.module.sass'

const keywords = [
  'Java', 'Angular', 'Javascript', 'PCF',
  'Firebase', 'Typescript', 'CI/CD', 'Kotlin',
  'Firestore', 'AWS', 'PWA', 'Spring Boot',
  'Rest API', 'DB2', 'SQL', 'NoSQL',
  'Git',
]

export default function Work() {
  return (
    <>
      <Card title="Keywords:">
        <ul className={styles.chipList} aria-label="keywords">
          {keywords.map((keyword) => (
            <li key={keyword} className={styles.chip}>
              {keyword}
            </li>
          ))}
        </ul>
      </Card>
      <WorkList />
    </>
  )
}
